spring.datasource.url=jdbc:postgresql://localhost:5432/blogapp2_test
spring.datasource.username=${DB_USERNAME:blogapp2_test}
spring.datasource.password=${DB_PASSWORD:testpassword}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
